### ISSUE TITLE
Consider using EXPIRE to reduce memory usage?

### ISSUE THREAD

**Issue by m3dh** [wallstreetcn/rate#1]
In the case of a big number of users.
Using our current implementation we may have to store two KVs per user.
If we use EXPIRE, then in the ideal case most of the user will not even exist in the Redis instance, would this be considerable? Or do you think it's too expensive to host expiration for each of the existing user hit rates?

**Comment by songrgg** [comment]
expire is already taken by `setex`, and the expiration time is double the rate limit bucket fill time.
```lua
local ttl = math.floor(fill_time*2)
...
redis.call("setex", tokens_key, ttl, new_tokens)
```
